### PR TITLE
Refactored `element.trigger()` into a feature complete Strategy

### PR DESCRIPTION
**Pull request by avoidwork**
- Refactored `element.trigger()` into a strategy which uses `CustomEvent` if available
- Normalized the `Event` shape between `CustomEvent` & `document.createEvent("HTMLEvents");`
- Fixing a reference error of `forEach()`
- Aligned variables because ... I do that

### CODE REVIEW

**Comment by remy** [comment]
Hmm, now get it back down to a few lines of code. Personally, I'd drop the CustomEvent if available. Keep it lean and mean. I'd also drop srcElement and currentTarget in favour of simplicity and KISS.

Brutal, eh :)

**Comment by avoidwork** [comment]
In this case I'd be concerned with 'complete' Events that have value to use in the real world. Events without target / src info have very little value.

The reason for the strategy can be summed up by the red box at the top of this page: https://developer.mozilla.org/en-US/docs/DOM/document.createEvent

**Comment by remy** [comment]
I've added event.target and a test for event delegation. I really appreciate pull requests - but given how minimal this lib is (ie. there's no way to remove event handlers - on purpose), I think it makes sense to leave the CustomEvent object out (for now).

**Comment by avoidwork** [comment]
I did some more testing with setting the variables, and it's not ideal. Each browser sets them once it goes through `dispatchEvent`, and some browser APIs are getters without setters.

**Pull request closed without merging**
