### PR TITLE
Added in some features!

### PR DESCRIPTION
**Pull request by stephenplusplus**
Hey,

I saw those "Gotchas" you listed, which motivated me to see if I could fix them. I also thought it'd be nice to add in Grunt to manage the build process. So, long story short:
- `npm install` -> fetches grunt, grunt-contrib-concat, and grunt-contrib-uglify
- created `/dist` and `/src` folders and moved the script to `/src/$.js`
- `grunt build` -> uglifies src/$.js to dist/$.js, dist/$.min.js, and $.js.map for source mapping
- created a `component.json` if you want to `bower register min.js git://github.com/remy/min.js.git`
- added chaining to triggers

I also added an internal empty element (not inserted on the document). When no results are returned from `$('a query')`, this empty div is returned, which will allow `.on` and `.trigger` to be used, as any other element. Also, this fake element is used if a user wants to say, simply `$.trigger` and `$.on`, without using `$` as a function.

I think that's about it, lemme know what you think.

### CODE REVIEW

**Comment by remy** [comment]
The fixing chaining is actually a lot simpler than that, I just changed the return line to this:

```
return r.length === 1 ? r[0] : r.length === 0 ? nodeList : r;
```

Works quite nicely (plus no internal element coming back - maybe good, maybe bad).

I'm reviewing a few pull requests, but want to keep this repo really simple still.

**Comment by remy** [comment]
Also, do you think it needs a sourcemap? I do like sourcemaps (even if it took me ages to get it working in JS Bin), but it's pretty small.

That said, I'm definitely adding in a bunch of these suggestions (even if I don't particularly pull - I appreciate it).

**Comment by remy** [comment]
Most of those changes are in - cheers for that.

**Comment by stephenplusplus** [comment]
Cool, I've been on the road for the last couple hours, so sorry to drop off from the discussion. Glad some of it was useful!

**Pull request closed without merging**
